import type { MenuItem, MenuCategory, Table, Reservation, KitchenOrder, FloorPlanTable, InventoryItem, StaffMember, Testimonial, GalleryImage, Restaurant } from "./types";

export const restaurant: Restaurant = {
  id: "futurebite-001",
  name: "FutureBite",
  tagline: "Dining, Reimagined.",
  description: "An extraordinary dining experience where precision, atmosphere, and cuisine converge to create unforgettable memories.",
  address: "123 Innovation Avenue",
  city: "Yangon, Myanmar",
  phone: "+95 9 123 456 789",
  email: "hello@futurebite.com",
  openingHours: [
    { day: "Monday", open: "6:00 PM", close: "11:00 PM", isClosed: false },
    { day: "Tuesday", open: "6:00 PM", close: "11:00 PM", isClosed: false },
    { day: "Wednesday", open: "6:00 PM", close: "11:00 PM", isClosed: false },
    { day: "Thursday", open: "6:00 PM", close: "11:00 PM", isClosed: false },
    { day: "Friday", open: "6:00 PM", close: "11:30 PM", isClosed: false },
    { day: "Saturday", open: "5:30 PM", close: "11:30 PM", isClosed: false },
    { day: "Sunday", open: "5:30 PM", close: "10:30 PM", isClosed: false },
  ],
  isOpen: true,
};

export const menuCategories: MenuCategory[] = [
  { id: "cat-1", name: "Starters", slug: "starters", description: "Begin your journey", displayOrder: 1 },
  { id: "cat-2", name: "Mains", slug: "mains", description: "The heart of the experience", displayOrder: 2 },
  { id: "cat-3", name: "Chef's Selection", slug: "chefs-selection", description: "Curated by our kitchen", displayOrder: 3 },
  { id: "cat-4", name: "Desserts", slug: "desserts", description: "A sweet conclusion", displayOrder: 4 },
  { id: "cat-5", name: "Drinks", slug: "drinks", description: "Crafted beverages", displayOrder: 5 },
];

export const menuItems: MenuItem[] = [
  {
    id: "dish-001",
    name: "Nebula Tartare",
    slug: "nebula-tartare",
    description: "Hand-cut wagyu beef tartare with black truffle, quail egg yolk, and shaved parmesan crisp. A constellation of flavors on a single plate.",
    price: 2800,
    category: "Starters",
    categorySlug: "starters",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
    ingredients: ["Wagyu beef", "Black truffle", "Quail egg", "Parmesan", "Capers", "Shallots"],
    allergens: ["Egg", "Dairy"],
    dietary: ["Gluten-free"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: 15,
  },
  {
    id: "dish-002",
    name: "Quantum Lobster Bisque",
    slug: "quantum-lobster-bisque",
    description: "Velvety bisque of Maine lobster, infused with cognac and finished with crème fraîche and micro herbs.",
    price: 2400,
    category: "Starters",
    categorySlug: "starters",
    imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80",
    ingredients: ["Maine lobster", "Cognac", "Heavy cream", "Micro herbs", "Crostini"],
    allergens: ["Shellfish", "Dairy", "Gluten"],
    dietary: [],
    isAvailable: true,
    isFeatured: false,
    preparationTime: 12,
  },
  {
    id: "dish-003",
    name: "Wagyu A5 Omakase",
    slug: "wagyu-a5-omakase",
    description: "Japanese A5 wagyu strip, charcoal-grilled to perfection, served with wasabi emulsion, pickled ginger, and seasonal vegetables.",
    price: 6800,
    category: "Mains",
    categorySlug: "mains",
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80",
    ingredients: ["A5 Wagyu strip", "Wasabi", "Ginger", "Seasonal vegetables", "Soy reduction"],
    allergens: ["Soy"],
    dietary: ["Gluten-free"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: 25,
  },
  {
    id: "dish-004",
    name: "Black Cod Stellaris",
    slug: "black-cod-stellaris",
    description: "Miso-marinated black cod, slow-roasted for 48 hours, served with dashi broth, shiso leaf, and yuzu foam.",
    price: 4200,
    category: "Mains",
    categorySlug: "mains",
    imageUrl: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80",
    ingredients: ["Black cod", "White miso", "Dashi", "Shiso", "Yuzu"],
    allergens: ["Fish", "Soy"],
    dietary: ["Gluten-free"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: 20,
  },
  {
    id: "dish-005",
    name: "Truffle Risotto Cosmos",
    slug: "truffle-risotto-cosmos",
    description: "Carnaroli rice risotto with black winter truffle, aged parmesan, and truffle oil. Rich, earthy, and deeply satisfying.",
    price: 3600,
    category: "Chef's Selection",
    categorySlug: "chefs-selection",
    imageUrl: "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&q=80",
    ingredients: ["Carnaroli rice", "Black winter truffle", "Parmesan", "Truffle oil", "Vegetable broth"],
    allergens: ["Dairy"],
    dietary: ["Vegetarian", "Gluten-free"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: 22,
  },
  {
    id: "dish-006",
    name: "Chocolate Eclipse",
    slug: "chocolate-eclipse",
    description: "Valrhona dark chocolate fondant with a molten center, accompanied by vanilla bean ice cream and gold leaf.",
    price: 1800,
    category: "Desserts",
    categorySlug: "desserts",
    imageUrl: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800&q=80",
    ingredients: ["Valrhona chocolate", "Butter", "Eggs", "Vanilla bean", "Gold leaf"],
    allergens: ["Dairy", "Egg", "Gluten"],
    dietary: [],
    isAvailable: true,
    isFeatured: true,
    preparationTime: 18,
  },
  {
    id: "dish-007",
    name: "Yuzu Panna Cotta Nebula",
    slug: "yuzu-panna-cotta",
    description: "Silky yuzu-infused panna cotta with matcha crumble and candied citrus zest. Light, fragrant, and elegant.",
    price: 1600,
    category: "Desserts",
    categorySlug: "desserts",
    imageUrl: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800&q=80",
    ingredients: ["Yuzu", "Cream", "Gelatin", "Matcha", "Candied citrus"],
    allergens: ["Dairy"],
    dietary: ["Gluten-free"],
    isAvailable: true,
    isFeatured: false,
    preparationTime: 10,
  },
  {
    id: "dish-008",
    name: "FutureBite Signature Cocktail",
    slug: "signature-cocktail",
    description: "Our signature blend of premium gin, elderflower, butterfly pea flower, and champagne. Changes color with a squeeze of lime.",
    price: 2200,
    category: "Drinks",
    categorySlug: "drinks",
    imageUrl: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=800&q=80",
    ingredients: ["Premium gin", "Elderflower", "Butterfly pea flower", "Champagne", "Lime"],
    allergens: [],
    dietary: ["Vegan"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: 5,
  },
];

export const tables: Table[] = [
  { id: "tbl-1", number: 1, capacity: 2, experience: "window", status: "available", location: "Window" },
  { id: "tbl-2", number: 2, capacity: 2, experience: "window", status: "available", location: "Window" },
  { id: "tbl-3", number: 3, capacity: 4, experience: "window", status: "reserved", location: "Window" },
  { id: "tbl-4", number: 4, capacity: 4, experience: "main", status: "available", location: "Main" },
  { id: "tbl-5", number: 5, capacity: 6, experience: "main", status: "available", location: "Main" },
  { id: "tbl-6", number: 6, capacity: 8, experience: "main", status: "reserved", location: "Main" },
  { id: "tbl-7", number: 7, capacity: 2, experience: "bar", status: "available", location: "Bar" },
  { id: "tbl-8", number: 8, capacity: 2, experience: "bar", status: "seated", location: "Bar" },
  { id: "tbl-9", number: 9, capacity: 10, experience: "private", status: "available", location: "Private Room" },
  { id: "tbl-10", number: 10, capacity: 12, experience: "private", status: "reserved", location: "Private Room" },
];

export const floorPlanTables: FloorPlanTable[] = [
  { id: "tbl-1", number: 1, capacity: 2, experience: "window", status: "available", x: 5, y: 10, width: 80, height: 60 },
  { id: "tbl-2", number: 2, capacity: 2, experience: "window", status: "available", x: 15, y: 10, width: 80, height: 60 },
  { id: "tbl-3", number: 3, capacity: 4, experience: "window", status: "reserved", x: 25, y: 10, width: 100, height: 80 },
  { id: "tbl-4", number: 4, capacity: 4, experience: "main", status: "available", x: 40, y: 30, width: 100, height: 80 },
  { id: "tbl-5", number: 5, capacity: 6, experience: "main", status: "available", x: 55, y: 30, width: 120, height: 80 },
  { id: "tbl-6", number: 6, capacity: 8, experience: "main", status: "reserved", x: 70, y: 30, width: 140, height: 80 },
  { id: "tbl-7", number: 7, capacity: 2, experience: "bar", status: "available", x: 10, y: 55, width: 80, height: 60 },
  { id: "tbl-8", number: 8, capacity: 2, experience: "bar", status: "seated", x: 25, y: 55, width: 80, height: 60 },
  { id: "tbl-9", number: 9, capacity: 10, experience: "private", status: "available", x: 80, y: 55, width: 160, height: 100 },
  { id: "tbl-10", number: 10, capacity: 12, experience: "private", status: "reserved", x: 80, y: 70, width: 160, height: 100 },
];

export const reservations: Reservation[] = [
  {
    id: "res-001",
    confirmationCode: "FB-2026-0001",
    customerId: "cust-001",
    customerName: "Sarah Chen",
    customerEmail: "sarah@email.com",
    customerPhone: "+95 9 111 111 111",
    date: "2026-09-04",
    time: "19:30",
    partySize: 2,
    tableId: "tbl-1",
    tableNumber: 1,
    experience: "window",
    specialRequests: "Anniversary dinner, window seat preferred",
    status: "confirmed",
    createdAt: "2026-09-01T10:00:00Z",
    updatedAt: "2026-09-01T10:00:00Z",
  },
  {
    id: "res-002",
    confirmationCode: "FB-2026-0002",
    customerId: "cust-002",
    customerName: "James Patel",
    customerEmail: "james@email.com",
    customerPhone: "+95 9 222 222 222",
    date: "2026-09-04",
    time: "20:00",
    partySize: 4,
    tableId: "tbl-4",
    tableNumber: 4,
    experience: "main",
    specialRequests: "",
    status: "confirmed",
    createdAt: "2026-09-02T14:30:00Z",
    updatedAt: "2026-09-02T14:30:00Z",
  },
  {
    id: "res-003",
    confirmationCode: "FB-2026-0003",
    customerId: "cust-003",
    customerName: "Lin Wei",
    customerEmail: "lin@email.com",
    customerPhone: "+95 9 333 333 333",
    date: "2026-09-05",
    time: "19:00",
    partySize: 6,
    tableId: "tbl-5",
    tableNumber: 5,
    experience: "main",
    specialRequests: "Business dinner, dietary restrictions: vegetarian",
    status: "confirmed",
    createdAt: "2026-09-03T09:15:00Z",
    updatedAt: "2026-09-03T09:15:00Z",
  },
];

export const kitchenOrders: KitchenOrder[] = [
  {
    id: "ord-001",
    orderNumber: "#1042",
    tableNumber: 8,
    items: [
      { id: "oi-1", name: "Wagyu A5 Omakase", quantity: 2, status: "preparing", specialInstructions: "Medium rare" },
      { id: "oi-2", name: "Truffle Risotto Cosmos", quantity: 1, status: "pending", specialInstructions: "" },
      { id: "oi-3", name: "Water", quantity: 2, status: "ready", specialInstructions: "Sparkling" },
    ],
    priority: "normal",
    status: "preparing",
    elapsed: 161,
    createdAt: new Date(Date.now() - 161000).toISOString(),
  },
  {
    id: "ord-002",
    orderNumber: "#1043",
    tableNumber: 3,
    items: [
      { id: "oi-4", name: "Nebula Tartare", quantity: 2, status: "pending", specialInstructions: "" },
      { id: "oi-5", name: "Quantum Lobster Bisque", quantity: 1, status: "pending", specialInstructions: "Extra croutons" },
    ],
    priority: "urgent",
    status: "pending",
    elapsed: 245,
    createdAt: new Date(Date.now() - 245000).toISOString(),
  },
  {
    id: "ord-003",
    orderNumber: "#1044",
    tableNumber: 6,
    items: [
      { id: "oi-6", name: "Black Cod Stellaris", quantity: 4, status: "ready", specialInstructions: "" },
      { id: "oi-7", name: "Chocolate Eclipse", quantity: 2, status: "pending", specialInstructions: "Allergen: nuts" },
    ],
    priority: "normal",
    status: "plating",
    elapsed: 89,
    createdAt: new Date(Date.now() - 89000).toISOString(),
  },
];

export const inventoryItems: InventoryItem[] = [
  { id: "inv-1", name: "Wagyu Beef A5", unit: "kg", currentStock: 4.5, minimumStock: 2, cost: 180, supplier: "Premium Meats Co.", status: "healthy", lastUpdated: "2026-09-04" },
  { id: "inv-2", name: "Black Winter Truffle", unit: "g", currentStock: 120, minimumStock: 50, cost: 8.5, supplier: "Truffle House", status: "healthy", lastUpdated: "2026-09-04" },
  { id: "inv-3", name: "Maine Lobster", unit: "pcs", currentStock: 8, minimumStock: 5, cost: 45, supplier: "Ocean Fresh", status: "low", lastUpdated: "2026-09-03" },
  { id: "inv-4", name: "Valrhona Dark Chocolate", unit: "kg", currentStock: 2.1, minimumStock: 1, cost: 35, supplier: "Choco Artisans", status: "healthy", lastUpdated: "2026-09-04" },
  { id: "inv-5", name: "Champagne (Moët)", unit: "btl", currentStock: 3, minimumStock: 6, cost: 55, supplier: "Fine Wines Ltd.", status: "critical", lastUpdated: "2026-09-02" },
  { id: "inv-6", name: "Carnaroli Rice", unit: "kg", currentStock: 5.8, minimumStock: 3, cost: 12, supplier: "Italian Imports", status: "healthy", lastUpdated: "2026-09-04" },
  { id: "inv-7", name: "Yuzu Juice", unit: "L", currentStock: 0.8, minimumStock: 1, cost: 28, supplier: "Asian Ingredients", status: "critical", lastUpdated: "2026-09-03" },
];

export const staffMembers: StaffMember[] = [
  { id: "staff-1", name: "Alex Kim", email: "alex@futurebite.com", role: "admin", phone: "+95 9 100 100 100", isActive: true, shift: "All Day" },
  { id: "staff-2", name: "Chef Nakamura", email: "chef.nakamura@futurebite.com", role: "kitchen", phone: "+95 9 200 200 200", isActive: true, shift: "Evening" },
  { id: "staff-3", name: "Maya Thompson", email: "maya@futurebite.com", role: "manager", phone: "+95 9 300 300 300", isActive: true, shift: "Evening" },
  { id: "staff-4", name: "Soo-jin Park", email: "soojin@futurebite.com", role: "waiter", phone: "+95 9 400 400 400", isActive: true, shift: "Evening" },
  { id: "staff-5", name: "Daniel Oo", email: "daniel@futurebite.com", role: "host", phone: "+95 9 500 500 500", isActive: true, shift: "Evening" },
  { id: "staff-6", name: "Rachel Lim", email: "rachel@futurebite.com", role: "kitchen", phone: "+95 9 600 600 600", isActive: true, shift: "Evening" },
];

export const testimonials: Testimonial[] = [
  {
    id: "test-1",
    name: "Aung Myo",
    rating: 5,
    text: "An absolutely extraordinary evening. The Wagyu A5 was the finest I have ever tasted. The atmosphere is unlike anything in Yangon — pure elegance.",
    date: "2026-08-28",
  },
  {
    id: "test-2",
    name: "Priya Sharma",
    rating: 5,
    text: "FutureBite redefined what dining means to us. Every course told a story. We will be back next month.",
    date: "2026-08-22",
  },
  {
    id: "test-3",
    name: "David Chen",
    rating: 5,
    text: "Impeccable service, stunning presentation, and flavors that linger in your memory. A true gem in Yangon.",
    date: "2026-08-15",
  },
];

export const galleryImages: GalleryImage[] = [
  { id: "g-1", url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&q=90", alt: "Elegant dining room with ambient lighting", category: "restaurant" },
  { id: "g-2", url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&q=90", alt: "Beautifully plated wagyu dish", category: "food" },
  { id: "g-3", url: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&q=80", alt: "Chef preparing a dish", category: "kitchen" },
  { id: "g-4", url: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=1200&q=90", alt: "Private dining room", category: "restaurant" },
  { id: "g-5", url: "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&q=80", alt: "Dessert presentation", category: "food" },
  { id: "g-6", url: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=90", alt: "Candlelit table setting", category: "atmosphere" },
  { id: "g-7", url: "https://images.unsplash.com/photo-1583394293214-28ded15ee548?w=800&q=80", alt: "Head chef in the kitchen", category: "chef" },
  { id: "g-8", url: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=1200&q=90", alt: "Cocktail preparation", category: "food" },
];

export const reservationTimeSlots = [
  "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30",
];

export const adminStats = {
  todayReservations: 12,
  todayOrders: 47,
  currentCovers: 28,
  kitchenQueue: 3,
  revenue: 2850000,
  averageOrderValue: 60600,
  occupancy: 78,
  popularDishes: [
    { name: "Wagyu A5 Omakase", orders: 18 },
    { name: "Truffle Risotto Cosmos", orders: 15 },
    { name: "Black Cod Stellaris", orders: 12 },
    { name: "Nebula Tartare", orders: 10 },
    { name: "Chocolate Eclipse", orders: 9 },
  ],
};
