-- Cloudflare D1 (SQLite) schema for Futuristic Restaurant

PRAGMA foreign_keys = ON;

-- Users
CREATE TABLE users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'user', -- user | admin
  barcode TEXT UNIQUE,
  qrcode TEXT UNIQUE,
  points INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX idx_users_email ON users(email);

-- Admins (subset of users or separate table for extra metadata)
CREATE TABLE admins (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  permissions TEXT,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Dishes
CREATE TABLE dishes (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price INTEGER NOT NULL, -- cents
  points INTEGER DEFAULT 0,
  category TEXT,
  image_url TEXT,
  available INTEGER DEFAULT 1,
  created_at DATETIME DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX idx_dishes_category ON dishes(category);

-- Tables
CREATE TABLE tables (
  id TEXT PRIMARY KEY,
  table_number INTEGER UNIQUE,
  qrcode TEXT UNIQUE,
  seats INTEGER DEFAULT 4,
  status TEXT DEFAULT 'available' -- available|booked|occupied
);
CREATE INDEX idx_tables_number ON tables(table_number);

-- Bookings
CREATE TABLE bookings (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  table_id TEXT NOT NULL,
  booking_time DATETIME NOT NULL,
  status TEXT DEFAULT 'booked', -- booked|occupied|cancelled
  created_at DATETIME DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY(user_id) REFERENCES users(id),
  FOREIGN KEY(table_id) REFERENCES tables(id)
);
CREATE INDEX idx_bookings_time ON bookings(booking_time);

-- Orders
CREATE TABLE orders (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  table_id TEXT,
  total_amount INTEGER NOT NULL,
  status TEXT DEFAULT 'pending', -- pending|cooking|completed|rejected
  created_at DATETIME DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY(user_id) REFERENCES users(id),
  FOREIGN KEY(table_id) REFERENCES tables(id)
);
CREATE INDEX idx_orders_status ON orders(status);

-- Order Items
CREATE TABLE order_items (
  id TEXT PRIMARY KEY,
  order_id TEXT NOT NULL,
  dish_id TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  price INTEGER NOT NULL,
  points INTEGER DEFAULT 0,
  FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,
  FOREIGN KEY(dish_id) REFERENCES dishes(id)
);
CREATE INDEX idx_order_items_order ON order_items(order_id);

-- Supplies
CREATE TABLE supplies (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  quantity INTEGER DEFAULT 0,
  restock_date DATETIME,
  price INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- Ratings
CREATE TABLE ratings (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  rating INTEGER NOT NULL CHECK(rating >= 1 AND rating <= 5),
  comment TEXT,
  created_at DATETIME DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY(user_id) REFERENCES users(id)
);

-- Daily Sales
CREATE TABLE daily_sales (
  id TEXT PRIMARY KEY,
  date TEXT NOT NULL,
  total_income INTEGER DEFAULT 0,
  total_expense INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- Indexes for analytics
CREATE INDEX idx_daily_sales_date ON daily_sales(date);

-- Order history summary table (denormalized optional)
CREATE TABLE order_history (
  id TEXT PRIMARY KEY,
  order_id TEXT NOT NULL,
  user_id TEXT,
  table_id TEXT,
  summary TEXT,
  created_at DATETIME DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- Notes: UUIDs are generated by application layer (Workers). Use TEXT for PKs.
